version: '3.8'
services:
  admin_app_dev:
    build:
      dockerfile: ./Docker/dev.dockerfile
      context: ../
    restart: always
    environment:
      DEBUG_MODE: "False"
      VERBOSITY: "info"
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
